
export const CREATE_TABLES: string[]=[

    'CREATE TABLE IF NOT EXISTS USER(USER_ID TEXT PRIMARY KEY, NAME TEXT NOT NULL, EMAIL TEXT UNIQUE NOT NULL, AGE INTEGER NOT NULL, BLOOD_GROUP TEXT NOT NULL, PHONE_NUMBER TEXT NOT NULL, PASSWORD TEXT NOT NULL, IS_AUTH BOOLEAN);',
    'CREATE TABLE IF NOT EXISTS MEDICINES(MEDICINE_ID TEXT PRIMARY KEY, MEDICINE_NAME TEXT NOT NULL, TIME_TO_TAKE TEXT,COMPLETION TEXT);',
    'CREATE TABLE IF NOT EXISTS EMERGENCY(ID TEXT PRIMARY KEY, NAME TEXT NOT NULL, PHONE_NUMBER TEXT NOT NULL, ALTERNATE_PHONE_NUMBER TEXT NOT NULL, AGE INTEGER NOT NULL, ADDRESS TEXT NOT NULL, LOCATION TEXT NOT NULL, REPORT TEXT);',
    'CREATE TABLE IF NOT EXISTS DOCTORS(DOCT_ID TEXT PRIMARY KEY, NAME TEXT NOT NULL, ADDRESS TEXT NOT NULL, PHONE_NUMBER TEXT NOT NULL, SPECIALIZED TEXT NOT NULL);',
    'CREATE TABLE IF NOT EXISTS DIETS(DIET_ID TEXT NOT NULL, COURSE_NAME TEXT NOT NULL, DURATION TEXT NOT NULL, DESCRIPTION TEXT NOT NULL, VIDEOS TEXT);'
];

export const CLEAR_TABLES: string[]=[
    'DELETE FROM USER;',
    'DELETE FROM MEDICINES;',
    'DELETE FROM EMERGENCY;',
    'DELETE FROM DOCTORS;',
    'DELETE FROM DIETS;',
]